# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import smart_selects.db_fields
import datetime
import jobportal.models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('admin_username', models.CharField(max_length=50, null=True, verbose_name=b'Admin Name', blank=True)),
                ('position', models.CharField(max_length=60, null=True, blank=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='AlumJobRelation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('placed_init', models.BooleanField(default=False)),
                ('placed_approved', models.BooleanField(default=False)),
                ('shortlist_status', models.BooleanField(default=False)),
                ('ppo_init', models.BooleanField(default=False)),
                ('ppo_approved', models.NullBooleanField(default=None)),
                ('ppo_accepted', models.NullBooleanField(default=None)),
                ('cv_field', models.FilePathField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('iitg_webmail', models.CharField(max_length=50, verbose_name=b'IITG Webmail', blank=True)),
                ('alternate_email', models.EmailField(max_length=254, verbose_name=b'Alternate Email', blank=True)),
                ('department', models.CharField(blank=True, max_length=25, verbose_name=b'Department', choices=[(b'BT', b'Biotechnology[BT]'), (b'CL', b'Chemical[CL]'), (b'CHE', b'Chemistry[CHE]'), (b'CE', b'Civil[CE]'), (b'CSE', b'Computer Science[CSE]'), (b'DD', b'Design[DD]'), (b'EEE', b'Electrical[EEE]'), (b'ECE', b'Electronics[ECE]'), (b'HSS', b'Humanities & Social Sciences[HSS]'), (b'MA', b'Mathematics[MA]'), (b'ME', b'Mechanical[ME]'), (b'EP', b'Physics[EP]')])),
                ('programme', models.CharField(blank=True, max_length=10, choices=[(b'BTECH', b'B.Tech.'), (b'MTECH', b'M.Tech.'), (b'PHD', b'Ph.D.')])),
                ('linkedin_link', models.URLField(max_length=254, null=True, blank=True)),
            ],
            options={
                'ordering': ['user', 'iitg_webmail', 'alternate_email', 'department'],
                'managed': True,
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password_copy', models.CharField(default=b'password', max_length=30, null=True, blank=True)),
                ('company_name', models.CharField(max_length=30, null=True, verbose_name=b'Company', blank=True)),
                ('description', models.TextField(null=True, verbose_name=b'Brief Writeup on organization', blank=True)),
                ('postal_address', models.TextField(null=True, verbose_name=b'Postal Address', blank=True)),
                ('website', models.CharField(default=b'www.example.com', max_length=100)),
                ('organization_type', models.CharField(default=b'PSU', max_length=20, verbose_name=b'Type of Organization', blank=True, choices=[(b'Private', b'Private'), (b'Government', b'Government'), (b'PSU', b'PSU'), (b'MNC(Indian Origin)', b'MNC(Indian Origin)'), (b'MNC(Foreign Origin)', b'MNC(Indian Origin)'), (b'NGO', b'NGO'), (b'Other', b'Other')])),
                ('industry_sector', models.CharField(default=b'IT', max_length=25, verbose_name=b'Industry Sector', blank=True, choices=[(b'Core Engg', b'Core Engg'), (b'IT', b'IT'), (b'Analytics', b'Analytics'), (b'Management', b'Management'), (b'Finance', b'Finance'), (b'Education', b'Education'), (b'Consulting', b'Consulting'), (b'R&D', b'R&D'), (b'Oil and Gas', b'Oil and Gas'), (b'Ecommerce', b'Ecommerce'), (b'FMCG', b'FMCG'), (b'Manufacturing', b'Manufacturing'), (b'Telecom', b'Telecom'), (b'Other', b'Other')])),
                ('head_hr_name', models.CharField(max_length=20, null=True, blank=True)),
                ('head_hr_email', models.CharField(max_length=60, null=True, blank=True)),
                ('head_hr_designation', models.CharField(max_length=30, null=True, blank=True)),
                ('head_hr_mobile', models.CharField(max_length=12, null=True, blank=True)),
                ('head_hr_fax', models.CharField(max_length=15, null=True, blank=True)),
                ('first_hr_name', models.CharField(max_length=20, null=True, blank=True)),
                ('first_hr_email', models.CharField(max_length=60, null=True, blank=True)),
                ('first_hr_designation', models.CharField(max_length=30, null=True, blank=True)),
                ('first_hr_mobile', models.CharField(max_length=12, null=True, blank=True)),
                ('first_hr_fax', models.CharField(max_length=15, null=True, blank=True)),
                ('second_hr_name', models.CharField(max_length=20, null=True, blank=True)),
                ('second_hr_email', models.CharField(max_length=60, null=True, blank=True)),
                ('second_hr_designation', models.CharField(max_length=30, null=True, blank=True)),
                ('second_hr_mobile', models.CharField(max_length=12, null=True, blank=True)),
                ('second_hr_fax', models.CharField(max_length=15, null=True, blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('sent_back', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyReg',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company_name_reg', models.CharField(max_length=30, null=True, verbose_name=b'Company', blank=True)),
                ('description_reg', models.TextField(null=True, verbose_name=b'Brief Writeup on organization', blank=True)),
                ('postal_address_reg', models.TextField(null=True, verbose_name=b'Postal Address', blank=True)),
                ('website_reg', models.CharField(default=b'www.example.com', max_length=100)),
                ('organization_type_reg', models.CharField(default=b'PSU', max_length=20, verbose_name=b'Type of Organization', blank=True, choices=[(b'Private', b'Private'), (b'Government', b'Government'), (b'PSU', b'PSU'), (b'MNC(Indian Origin)', b'MNC(Indian Origin)'), (b'MNC(Foreign Origin)', b'MNC(Indian Origin)'), (b'NGO', b'NGO'), (b'Other', b'Other')])),
                ('industry_sector_reg', models.CharField(default=b'IT', max_length=25, verbose_name=b'Industry Sector', blank=True, choices=[(b'Core Engg', b'Core Engg'), (b'IT', b'IT'), (b'Analytics', b'Analytics'), (b'Management', b'Management'), (b'Finance', b'Finance'), (b'Education', b'Education'), (b'Consulting', b'Consulting'), (b'R&D', b'R&D'), (b'Oil and Gas', b'Oil and Gas'), (b'Ecommerce', b'Ecommerce'), (b'FMCG', b'FMCG'), (b'Manufacturing', b'Manufacturing'), (b'Telecom', b'Telecom'), (b'Other', b'Other')])),
                ('head_hr_name_reg', models.CharField(max_length=20, null=True, blank=True)),
                ('head_hr_email_reg', models.CharField(max_length=60, null=True, blank=True)),
                ('head_hr_designation_reg', models.CharField(max_length=30, null=True, blank=True)),
                ('head_hr_mobile_reg', models.CharField(max_length=12, null=True, blank=True)),
                ('head_hr_fax_reg', models.CharField(max_length=15, null=True, blank=True)),
                ('first_hr_name_reg', models.CharField(max_length=20, null=True, blank=True)),
                ('first_hr_email_reg', models.CharField(max_length=60, null=True, blank=True)),
                ('first_hr_designation_reg', models.CharField(max_length=30, null=True, blank=True)),
                ('first_hr_mobile_reg', models.CharField(max_length=12, null=True, blank=True)),
                ('first_hr_fax_reg', models.CharField(max_length=15, null=True, blank=True)),
                ('second_hr_name_reg', models.CharField(max_length=20, null=True, blank=True)),
                ('second_hr_email_reg', models.CharField(max_length=60, null=True, blank=True)),
                ('second_hr_designation_reg', models.CharField(max_length=30, null=True, blank=True)),
                ('second_hr_mobile_reg', models.CharField(max_length=12, null=True, blank=True)),
                ('second_hr_fax_reg', models.CharField(max_length=15, null=True, blank=True)),
            ],
            options={
                'verbose_name_plural': 'CompaniesReg',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dept', models.CharField(max_length=40)),
                ('dept_code', models.CharField(unique=True, max_length=4)),
                ('dept_minor_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('date3', models.DateField()),
                ('final_date', models.DateField(null=True, blank=True)),
                ('finalised', models.BooleanField(default=False)),
                ('alum_owner', models.ForeignKey(blank=True, to='jobportal.Alumni', null=True)),
                ('company_owner', models.ForeignKey(blank=True, to='jobportal.Company', null=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('posted_by_alumnus', models.BooleanField(default=False, verbose_name=b'Posted by Alum')),
                ('posted_by_company', models.BooleanField(default=False, verbose_name=b'Posted by Company')),
                ('open_for_alum', models.BooleanField(default=False, verbose_name=b'Open For Alumni')),
                ('open_for_studs', models.BooleanField(default=True)),
                ('description', models.TextField(null=True, verbose_name=b'Job Description', blank=True)),
                ('designation', models.CharField(max_length=50, null=True, verbose_name=b'Job Title/Designation', blank=True)),
                ('cpi_shortlist', models.BooleanField(default=False, choices=[(b'True', b'YES'), (b'False', b'No')])),
                ('minimum_cpi', models.DecimalField(default=0.0, max_digits=4, decimal_places=2, blank=True)),
                ('percentage_x', models.DecimalField(default=0.0, null=True, max_digits=5, decimal_places=2)),
                ('percentage_xii', models.DecimalField(default=0.0, null=True, max_digits=5, decimal_places=2)),
                ('num_openings', models.DecimalField(null=True, max_digits=3, decimal_places=0)),
                ('other_requirements', models.TextField(default=b'', max_length=100, null=True)),
                ('currency', models.CharField(default=b'INR', max_length=15, null=True)),
                ('ctc_btech', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('ctc_mtech', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('ctc_msc', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('ctc_ma', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('ctc_phd', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('gross_btech', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('gross_mtech', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('gross_msc', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('gross_ma', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('gross_phd', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('take_home_during_training', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('take_home_after_training', models.DecimalField(default=0.0, null=True, max_digits=12, decimal_places=2)),
                ('bonus', models.DecimalField(default=0.0, null=True, verbose_name=b'Bonus/Perks/Incentives', max_digits=12, decimal_places=2)),
                ('bond', models.NullBooleanField(default=False, choices=[(b'True', b'YES'), (b'False', b'No')])),
                ('bond_details', models.TextField(max_length=200, null=True, blank=True)),
                ('profile_name', models.CharField(default=b'profile_name', max_length=15)),
                ('posted_on', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('approved', models.NullBooleanField(default=None)),
                ('approved_on', models.DateField(null=True, blank=True)),
                ('sent_back', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(null=True, blank=True)),
                ('opening_date', models.DateField(default=datetime.date(2017, 1, 1), null=True, blank=True)),
                ('application_deadline', models.DateField(default=datetime.date(2017, 1, 1), null=True, blank=True)),
                ('alum_owner', models.ForeignKey(related_name='owner', blank=True, to='jobportal.Alumni', null=True)),
                ('alums', models.ManyToManyField(to='jobportal.Alumni', through='jobportal.AlumJobRelation', blank=True)),
                ('company_owner', models.ForeignKey(blank=True, to='jobportal.Company', null=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=10, blank=True)),
                ('dept', smart_selects.db_fields.ChainedForeignKey(chained_model_field=b'year', to='jobportal.Department', chained_field=b'year')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('roll_no', models.DecimalField(default=0, unique=True, verbose_name=b'Roll No', max_digits=10, decimal_places=0)),
                ('first_name', models.CharField(default=b'', max_length=20, blank=True)),
                ('middle_name', models.CharField(default=b'', max_length=20, blank=True)),
                ('last_name', models.CharField(default=b'', max_length=20, blank=True)),
                ('dob', models.DateField(default=django.utils.timezone.now, blank=True)),
                ('sex', models.CharField(default=b'M', max_length=1, choices=[(b'M', b'Male'), (b'F', b'Female')])),
                ('category', models.CharField(default=b'GEN', max_length=10, choices=[(b'GEN', b'GEN'), (b'OBC', b'OBC'), (b'SC', b'SC'), (b'ST', b'ST'), (b'PH', b'PH'), (b'Foreign', b'Foreign')])),
                ('nationality', models.CharField(default=b'INDIA', max_length=15, blank=True)),
                ('jee_air_rank', models.DecimalField(default=0, max_digits=6, decimal_places=0)),
                ('hostel', models.CharField(default=b'', max_length=25, blank=True, choices=[(b'Barak', b'Barak'), (b'Brahmaputra', b'Brahmaputra'), (b'Dhansiri', b'Dhansiri'), (b'Dibang', b'Dibang'), (b'Dihing', b'Dihing'), (b'Kameng', b'Kameng'), (b'Kapili', b'Kapili'), (b'Lohit', b'Lohit'), (b'Manas', b'Manas'), (b"Married Scholar's Hostel", b"Married Scholar's Hostel"), (b'Siang', b'Siang'), (b'Subansiri', b'Subansiri'), (b'Umiam', b'Umiam'), (b'Other', b'Other')])),
                ('room_no', models.CharField(default=b'', max_length=6, blank=True)),
                ('iitg_webmail', models.CharField(default=b'', unique=True, max_length=50, verbose_name=b'IITG Webmail')),
                ('alternative_email', models.CharField(max_length=50, null=True, verbose_name=b'Alternative Email', blank=True)),
                ('mobile_campus', models.CharField(max_length=16, blank=True)),
                ('mobile_campus_alternative', models.CharField(max_length=16, blank=True)),
                ('mobile_home', models.CharField(max_length=16, blank=True)),
                ('address_line1', models.CharField(default=b'', max_length=50, blank=True)),
                ('address_line2', models.CharField(default=b'', max_length=50, blank=True)),
                ('address_line3', models.CharField(default=b'', max_length=50, blank=True)),
                ('pin_code', models.DecimalField(default=781039, max_digits=10, decimal_places=0)),
                ('percentage_x', models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)),
                ('percentage_xii', models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)),
                ('board_x', models.CharField(default=b'CBSE', max_length=30, null=True, blank=True)),
                ('board_xii', models.CharField(default=b'CBSE', max_length=30, null=True, blank=True)),
                ('medium_x', models.CharField(default=b'English', max_length=30, null=True, blank=True)),
                ('medium_xii', models.CharField(default=b'English', max_length=30, null=True, blank=True)),
                ('passing_year_x', models.DecimalField(default=2003, max_digits=4, decimal_places=0, blank=True)),
                ('passing_year_xii', models.DecimalField(default=2003, max_digits=4, decimal_places=0, blank=True)),
                ('gap_in_study', models.BooleanField(default=False)),
                ('gap_reason', models.TextField(default=b'', max_length=100)),
                ('linkedin_link', models.URLField(max_length=254, null=True, blank=True)),
                ('cv1', models.FileField(null=True, upload_to=jobportal.models.generate_cv1filename, blank=True)),
                ('cv2', models.FileField(null=True, upload_to=jobportal.models.generate_cv2filename, blank=True)),
                ('placed', models.BooleanField(default=False)),
                ('intern2', models.BooleanField(default=False)),
                ('intern3', models.BooleanField(default=False)),
                ('company_count', models.DecimalField(default=0, max_digits=30, decimal_places=0, blank=True)),
                ('ppo', models.BooleanField(default=False, verbose_name=b'PPO')),
                ('cpi', models.DecimalField(default=0.0, null=True, max_digits=4, decimal_places=2, blank=True)),
                ('spi_1_sem', models.DecimalField(default=0.0, null=True, max_digits=4, decimal_places=2, blank=True)),
                ('spi_2_sem', models.DecimalField(default=0.0, null=True, max_digits=4, decimal_places=2, blank=True)),
                ('spi_3_sem', models.DecimalField(default=0.0, null=True, max_digits=4, decimal_places=2, blank=True)),
                ('spi_4_sem', models.DecimalField(default=0.0, null=True, max_digits=4, decimal_places=2, blank=True)),
                ('spi_5_sem', models.DecimalField(default=0.0, null=True, max_digits=4, decimal_places=2, blank=True)),
                ('spi_6_sem', models.DecimalField(default=0.0, null=True, max_digits=4, decimal_places=2, blank=True)),
                ('dept', models.ForeignKey(to='jobportal.Department', null=True)),
                ('minor_programme', models.ForeignKey(related_name='minor', blank=True, to='jobportal.Department', null=True)),
                ('prog', models.ForeignKey(related_name='major', to='jobportal.Programme', null=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentJobRelation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('placed_init', models.BooleanField(default=False)),
                ('placed_approved', models.NullBooleanField(default=None)),
                ('shortlist_status', models.BooleanField(default=False)),
                ('ppo_init', models.BooleanField(default=False)),
                ('ppo_approved', models.NullBooleanField(default=None)),
                ('ppo_accepted', models.NullBooleanField(default=None)),
                ('cv_field', models.FilePathField(null=True, blank=True)),
                ('cv1', models.BooleanField(default=False)),
                ('cv2', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, to='jobportal.Job', null=True)),
                ('stud', models.ForeignKey(blank=True, to='jobportal.Student', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('login_type', models.CharField(default=b'Current Student', max_length=20, choices=[(b'Current Student', b'Current Student'), (b'Alumni', b'Alumni'), (b'Company', b'Company'), (b'Admin', b'Admin')])),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('current_year', models.DecimalField(unique=True, null=True, max_digits=4, decimal_places=0)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, blank=True, to='jobportal.UserProfile'),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ForeignKey(to='jobportal.Year', null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='year',
            field=models.ForeignKey(to='jobportal.Year'),
        ),
        migrations.AddField(
            model_name='job',
            name='current_year',
            field=models.ManyToManyField(to='jobportal.Year'),
        ),
        migrations.AddField(
            model_name='job',
            name='dept',
            field=models.ManyToManyField(to='jobportal.Department'),
        ),
        migrations.AddField(
            model_name='job',
            name='prog',
            field=models.ManyToManyField(to='jobportal.Programme'),
        ),
        migrations.AddField(
            model_name='job',
            name='students',
            field=models.ManyToManyField(to='jobportal.Student', through='jobportal.StudentJobRelation', blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.ForeignKey(to='jobportal.Year'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(null=True, blank=True, to='jobportal.UserProfile'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='dept',
            field=models.ForeignKey(to='jobportal.Department', null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='prog',
            field=models.ForeignKey(to='jobportal.Programme', null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(null=True, blank=True, to='jobportal.UserProfile'),
        ),
        migrations.AddField(
            model_name='alumjobrelation',
            name='alum',
            field=models.ForeignKey(blank=True, to='jobportal.Alumni', null=True),
        ),
        migrations.AddField(
            model_name='alumjobrelation',
            name='job',
            field=models.ForeignKey(blank=True, to='jobportal.Job', null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(null=True, blank=True, to='jobportal.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('dept', 'year')]),
        ),
    ]
